#!/bin/sh
surfaceTransformPoints constant/triSurface/GliderAssembly.stl -scale '(0.01 0.01 0.01)' constant/triSurface/GliderAssembly.stl
surfaceTransformPoints constant/triSurface/GliderAssembly.stl -rollPitchYaw '(0 0 180)' constant/triSurface/GliderAssembly.stl
