#!/bin/sh
surfaceTransformPoints constant/triSurface/PropCCW.stl -scale '(0.01 0.01 0.01)' constant/triSurface/PropCCW.stl
surfaceTransformPoints constant/triSurface/PropCCW.stl -translate '(-0.038 0.00 0.00)' constant/triSurface/PropCCW.stl
surfaceTransformPoints constant/triSurface/PropCCW.stl -rollPitchYaw '(0 90 180)' constant/triSurface/PropCCW.stl
surfaceTransformPoints constant/triSurface/PropCCW.stl -rollPitchYaw '(0 0 180)' constant/triSurface/PropCCW.stl


